linters:
  enable:
    - gofumpt
    - gocyclo
    - revive
    - misspell
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 20

  staticcheck:
    go: 1.17
    checks: ["all"]

  gofumpt:
    lang-version: 1.17
    extra-rules: true
